# Generated by Django 3.2.8 on 2022-01-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promovalue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
